### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by designerx2** [trevordixon/excel.js#37]
Is Python required in the path to install and run this module? I received a screen full of errors while attempting to install this on Node v4.1.1 

The first line or the errors was: Error: Can't find Python executable "python". then at failNoPython 

Please advise. Thank you.

**Comment by floledermann** [comment]
Some dependency uses node-gyp to compile native modules. Follow the instructions [here](https://github.com/nodejs/node-gyp#installation) to get it running.
