### ISSUE TITLE
version libxmljs@0.14.3 fails to build on node v6

### ISSUE THREAD

**Issue by IrishAdo** [trevordixon/excel.js#43]
please update your package to the latest version of libxmljs
npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.14.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/input/npm-debug.log
npm install failed, trying again

**Comment by IrishAdo** [comment]
Fix has been pulled

**Comment by clickclickonsal** [comment]
https://www.npmjs.com/package/excel
This hasn't been published to npm yet.
