### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anibalvy** [trevordixon/excel.js#8]
I'm reading a file created with LibreOffice and I got this error

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: invalid signature: 0x4acf92ad (at position: 0x29)
    at Parse._readRecord (/test-fs/fsapp/node_modules/excel/node_modules/unzip/lib/parse.js:56:13)
    at /test-fs/fsapp/node_modules/excel/node_modules/unzip/node_modules/pullstream/pullstream.js:101:11
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Any suggestion?

**Comment by guitarama** [comment]
In case anyone stumbles on this error code with LibreOffice files, I ran into this with Apache POI project  as well.  To get around it, I renamed my .xlsx to .zip, unzipped, re-zipped, renamed from .zip to .xlsx and it worked.  Something about the way LibreOffice is compressing the output files.
